package server

import (
	"encoding/json"
	"io"

	"golang.org/x/net/context"
)

// Add is a function that takes two ints and returns an int.
func Add(a, b int) int { return a + b }

// Downstream represents a downstream service
type Downstream func(context.Context) int

// AddRequest can be autogenerated.
type AddRequest struct {
	A int `json:"a"`
	B int `json:"b"`
}

// AddResponse can be autogenerated.
type AddResponse struct {
	V int `json:"v"`
}

// AddService can be autogenerated.
func AddService(d Downstream) Service {
	return func(ctx context.Context, req Request) (Response, error) {
		addReq, ok := req.(AddRequest)
		if !ok {
			return nil, ErrBadCast
		}

		v := Add(d(ctx), Add(addReq.A, addReq.B))
		return AddResponse{v}, nil
	}
}

// AddCodecJSON can be autogenerated.
type AddCodecJSON struct{}

// Decode TODO
func (c *AddCodecJSON) Decode(_ context.Context, src io.Reader) (Request, error) {
	var req AddRequest
	if err := json.NewDecoder(src).Decode(&req); err != nil {
		return nil, err
	}
	return req, nil
}

// Encode TODO
func (c *AddCodecJSON) Encode(dst io.Writer, resp Response) error {
	addResp, ok := resp.(AddResponse)
	if !ok {
		return ErrBadCast
	}
	return json.NewEncoder(dst).Encode(addResp)
}
